REEMPLAZOS = {
        "coraz6on": "corazon",
        "croneo": "craneo",
        "pldstico": "plastico",
        "nrefux": "firefux",
        "Afiche": "Afiche",
        "brabado": "Grabado",
        "Grabado de lave": "Grabado de llave",
        "Champifién": "Champinon",
        "Cinturén": "Cinturon",
        "Champiion": "Champinon",
        "Champion": "Champinon",
        "Champirion": "Champinon",
        "wukin:": "wukin",
        "'Símbolo de mision": "Simbolo de mision",
        "Grabado de símbolo de mi:": "Grabado de simbolo de mision",
        "vinturén": "Cinturon",
        "Caja para kebab": "Cana para kebab",
        "misién": "mision",
        "'Simbolo": "Simbolo",
        "helado'": "helado",
        "Champiifion": "Champinon",
        "Caiia": "Cana",
        "coraz6n": "corazon",
        "brochete": "brocheta",
        "plstico": "plastico",
        "nrefux": "firefux",
        "Anche": "Afiche",
        "Ojo de fabhuritu pintado": "Ojo de fab'huritu pintado",
        "Pescado ala plancha en brocheta": "Pescado a la plancha en brocheta",
        "Cintur6n": "Cinturon",
        "croneo": "craneo",
        "crneo": "craneo",
        "Craneo der reno": "Craneo de reno",
        "Ankam:": "Ankama",
        "claveteado:": "claveteado",
        "misi6n": "mision",
        "Ilave": "llave",
        ")jo de fab'huritu pintado": "Ojo de fab'huritu pintado",
        "Seeneaidadvaadan": "Craneo de tymador",
        "Cajia para kebab": "Cana para kebab",
        "aquiero": "agujero",
        "Craneo det urikornio": "Craneo de urikornio",
        "- Craneo": "Craneo",
        "Cuero de urikornio": "Cuerno de urikornio",
        "sedimentacién": "sedimentacion",
        "Roca tallada en espinas de pesc": "Roca tallada en espinas de pescado",
        "Bot6n": "Boton",
        "Caparaz6n": "Caparazon",
        "Telade cuadros anudada": "Tela de cuadros anudada",
        "Espantapdjaros": "Espantapajaros",
        "pleaado": "plegado",
        "draaopavo": "Veleta de dragopavo",
        "Triao blanco vy nearo": "Trigo blanco y negro",
        "Crdneo": "Craneo",
        "*ruz de piedra rota": "Cruz de piedra rota",
        "Seamed nicatee": "Tetera con rayas",
        "ensanarentada": "ensangrentada",
        "Champifion rayadoee": "Champinon rayado",
        "Créneo": "Craneo",
        "Craneo de « ocra": "Craneo de ocra",
        "rosade": "rosa de",
        "See": "Rosa negra",
        "Este": "Dirigete hacia el Este",
        "Norte": "Dirigete hacia el Norte",
        "Oeste": "Dirigete hacia el Oeste",
        "el Sur": "Dirigete hacia el Sur",
        "é": "o",
        "ó": "o",
        "fi": "n"  # Excluyendo "firefux" caso especial
    }