COORDENADAS_ZAAP = [
    (-5, -23, "Llanura de los puerkazos"),
    (-46, 18, "Pueblo costero"),
    (15, -58, "Dunas de los Huesos"),
    (10, 22, "Ribera del golfo sufokeno"),
    (-20, -20, "Caminos Rocosos"),
    (-78, -41, "Burgo"),
    (-2, 0, "Pueblo de Amakna"),
    (1, -32, "Tainela"),
    (-1, 24, "Llanura de los escarahojas"),
    (7, -4, "Puerto de Madrestam"),
    (-5, -8, "Montana de los crujidores"),
    (-13, -28, "Sierra de cania"),
    (-1, 13, "Linde del Bosque Malefico"),
    (-3, -42, "Lago de Cania"),
    (-15, 25, "Tierras Desacralizadas"),
    (20, -29, "Pueblo de Pandala"),
    (35, 12, "Playa Tortuga"),
    (39, -82, "Arboleda Nevada"),
    (-31, -56, "Corazon Inmaculado"),
    (-46, 18, "Pueblo costero"),
    (-25, 12, "Camino de las caravanas"),
    (-26, 37, "Coraza"),
    (-16, 1, "Pueblo de los ganaderos"),
    (-27, -36, "Campos de cania"),
    (13, 26, "Sufokia"),
    (5, 7, "Rincon de los Jalatos"),
    (5, -18, "Ciudad de astrub"),
    (3, -5, "Castillo de Amakna"),
    (-17, -47, "Llanuras rocosas")
]
